server:
  port: 80

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #自定义路由， lb表示LoadBalancer
      routes:
        - id: index
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: product
          uri: lb://product-service
          predicates:
              - Path=/product/**

eureka:
  client:
    service-url:
      defaultZone: http://wzy1:2181/eureka/,http://wzy2:2182/eureka/,http://wzy3:2183/eureka/

