server:
  port: 80

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://wzy1:2181/eureka/

#自定义路由规则
zuul:
  routes:
    api-index:
      path: /index/**
      serviceId: index-service
    api-product:
      path: /product/**
      serviceId: product-service
  ignored-patterns: /*-service/**
  #处理请求头为空的问题
  sensitive-headers: #zuul默认屏蔽cookie，这里设置为空则取消黑名单，cookie就可以传递到下游服务
