
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

---

spring:
  profiles: productService1
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://wzy1:2181/eureka/

---

spring:
  profiles: productService2
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://wzy1:2181/eureka/

---

logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug